# Generated by Django 5.1.2 on 2024-10-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workentry',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workentry',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourlyrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
