# Generated by Django 5.1.2 on 2024-10-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_workentry_end_time_workentry_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workentry',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
